### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by clockwiser** [BohdanNikoletti/SFaceCompare#1]
When compile the example project, error happens.

************************************************************
ld: warning: ignoring file /Users/kinkeisei/swiftProj/SFaceCompare/SFaceCompare/SameFace.framework/SameFace, file was built for x86_64 which is not the architecture being linked (arm64): /Users/kinkeisei/swiftProj/SFaceCompare/SFaceCompare/SameFace.framework/SameFace
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_OpenCVWrapper", referenced from:
      objc-class-ref in SFaceCompare(SFaceCompare.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by clockwiser** [comment]
It seems like an architecture problem. Xcode is linking to ipad 6, so what is wrong with the architecture?

**Comment by BohdanNikoletti** [comment]
@clockwiser  You are right! This is problem on our side. I'm going to fix it ASAP. Stay tuned.

**Comment by BohdanNikoletti** [comment]
Fixed in new version
