### ISSUE TITLE
Wrong Face Results count: Founded - 0 | Required - 1.

### ISSUE THREAD

**Issue by Er-Developer** [BohdanNikoletti/SFaceCompare#10]
Hi There,
Thank-you for sharing such great library. Could you please help me in below mentioned concern. 
On iPhone face matching not working. Please find image in attachment demonstrating same. Same functionality is working fine on simulator(iPhoneX). Error details mentioned below:

1. [FaceDetectionOperation.swift#main()#61]-E: Wrong Face Results count: Founded - 0 | Required - 1.
Code Line:  // Need check results only if objectsCountToDetect isn't default
            if self.objectsCountToDetect != 0 {
                guard results.count == self.objectsCountToDetect else {
                    **Logger.e("Wrong Face Results count: Founded - \(results.count) | Required - \(self.objectsCountToDetect)")
                    return**
                }
            }

Device and Xcode Details whom facing issue mentioned below:
1. iPhone 6S.
2. Xcode 10.2.1

Really appreciates for such great code. Thank-you in advance.

![IMG_DD8AA0432FB7-1](https://user-images.githubusercontent.com/16059532/59027973-0605b080-8878-11e9-8544-4582bda4a972.jpeg)

**Comment by Er-Developer** [comment]
Hi There,
Can you please help me. Thank-you

**Comment by BohdanNikoletti** [comment]
Hi. I'm using apple's [Vision](https://developer.apple.com/documentation/vision) to detect faces. So it's strange that faces can not be founded.

**Comment by BohdanNikoletti** [comment]
Seems that I'm luckier than you. Or that was something wrong with the quality of your photo.
![IMG_6120](https://user-images.githubusercontent.com/16256553/60130513-07076f00-97a0-11e9-931f-2fc31f783243.PNG)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16256553/60131913-205dea80-97a3-11e9-96ad-9d92b639c1a8.gif)
