### ISSUE TITLE
Hi There,

### ISSUE THREAD

**Issue by Er-Developer** [BohdanNikoletti/SFaceCompare#11]
Hi There,
Can you please help me. Thank-you

_Originally posted by @Er-Developer in https://github.com/BohdanNikoletti/SFaceCompare/issues/10#issuecomment-501561892_

**Comment by BohdanNikoletti** [comment]
Hi. [answered here](https://github.com/BohdanNikoletti/SFaceCompare/issues/10#issuecomment-501769760)
