### ISSUE TITLE
Unexpectedly found nil on class var urlOfModelInThisBundle 

### ISSUE THREAD

**Issue by syafieqq** [BohdanNikoletti/SFaceCompare#12]
Hello there, had tried your library today, and got error nil on class var urlOfModelInThisBundle.
but sometimes its work well, but most of the time got this error.
Both images are filled with an image that contains a valid and clear face

![Screenshot 2019-06-13 at 4 12 10 PM](https://user-images.githubusercontent.com/22884210/59415575-50e27380-8df6-11e9-9c1a-fc9245f9d74c.png)

**Comment by BohdanNikoletti** [comment]
Duplicate. Pls read [this](https://github.com/BohdanNikoletti/SFaceCompare/issues/4). Thanks.
