### ISSUE TITLE
Add mention in READ.me about including Face.ml to project

### ISSUE THREAD

**Issue by jainamSynoverge** [BohdanNikoletti/SFaceCompare#13]
@BohdanNikoletti & @Thromkir  I m getting an error in Faces model, I attached a screenshot of that error below,

can you please let me know how to create our own model for face verification or face comparison?

![Screenshot 2019-06-25 at 1 33 27 PM](https://user-images.githubusercontent.com/46776325/60080731-1cec4400-974e-11e9-8510-85026df1ddcc.png)

**Comment by BohdanNikoletti** [comment]
To solve your issue pls [read](https://github.com/BohdanNikoletti/SFaceCompare/issues/4).

**Comment by jainamSynoverge** [comment]
hello @BohdanNikoletti, I read given link and put Faces.mlmodel in the app as you said still getting the same error.

can you please let me know how to create our own model for face verification or face comparison?

**Comment by BohdanNikoletti** [comment]
> hello @BohdanNikoletti, I read given link and put Faces.mlmodel in the app as you said still getting the same error.
> 
> can you please let me know how to create our own model for face verification or face comparison?

I've used optimised ML model provided by OpenFace. In case you need your own model. You should go deep in ML)
