### ISSUE TITLE
Xcode 11.0 and Swift 5.1 support

### ISSUE THREAD

**Issue by ankushmittal87** [BohdanNikoletti/SFaceCompare#14]
Hi, 

I am trying build SFaceCompare but it is giving me some compiler version mismatch error.

I tried it with Xcode 10.1 and swift version 4. But when I got to know that I need to run SFaceCompare with Swift 5 then I switched to Xcode 11.0 beta version with Swift 5.

I am still facing the issue. Please help me in resolving this one.

Thank you in advance,
Ankush Mittal

**Comment by BohdanNikoletti** [comment]
Swift 5 is available in Version 10.2.1 (10E1001). I haven't built this framework under xCode beta.

**Comment by ankushmittal87** [comment]
Many thanks for such quick reply. I used xcode 10.2.1 and successfully build the project.

**Comment by rideflag-sheharyar-irfan** [comment]
Any update on this? Not working on new Xcode 11 beta's. Need swift 5.1 support

**Comment by AnteCepic** [comment]
Hello Bohdan, when can we expect support for swift 5.1? Xcode 11 is out.
Thanks!

**Comment by BohdanNikoletti** [comment]
Support is available in latest release.
