### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Harishreddy122** [BohdanNikoletti/SFaceCompare#15]
This is not working for me giving  results as matching for all the faces

**Comment by BohdanNikoletti** [comment]
This lib is build on top of [OpenFace  ML](https://www.researchgate.net/publication/328186690_Evaluating_OpenFace_an_open-source_automatic_facial_comparison_algorithm_for_forensics).

**Comment by BohdanNikoletti** [comment]
I can't improve it for now and in nearest feature.
