### ISSUE TITLE
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler: 

### ISSUE THREAD

**Issue by sanaSajwan7** [BohdanNikoletti/SFaceCompare#16]
I am getting this error, please do update. I am using cocoapod 
@BohdanNikoletti Please check this one

**Comment by ricardoburgos** [comment]
I have the same problem, can you please recompile the project ?

**Comment by samuelail** [comment]
Update your Xcode to the latest one. open the project in the updated Xcode and build again.

**Comment by samuelail** [comment]
Update your Xcode to the latest one. open the project in the updated Xcode and build again.

**Comment by ricardoburgos** [comment]
> Update your Xcode to the latest one. open the project in the updated Xcode and build again.

Hi Samuel, I have the latest xcode, Version 11.1 but the alert error still appear, mi pod file is something like this, do you see something wrong ? 

Thanks

    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '11.3'
    use_frameworks!

    target 'SFaceCompare_Example' do
        pod 'SFaceCompare'

        target 'SFaceCompare_Tests' do
        inherit! :search_paths

        pod 'Quick'
        pod 'Nimble'
      end
    end

**Comment by samuelail** [comment]
This is how my your pod file should look ( if you didn't change anything after downloading the example)

platform :ios, '11.3'

use_frameworks!

target 'SFaceCompare_Example' do
  pod 'SFaceCompare', :path => '../'

  target 'SFaceCompare_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end

You can also go further to change the build system from "New Build System" to " Legacy Build System". It fixes a lot of issues. 

Files > workspace settings >

**Comment by ricardoburgos** [comment]
Hi Samuel, yes it was my mistake, another thing, how can I improve the model, I see that is not matching the faces well all the time.

Thanks

**Comment by samuelail** [comment]
I think for that, you will have to train your own model. You can use Playground to train your model I think.

**Comment by zzjf** [comment]
![image](https://user-images.githubusercontent.com/6127294/68187788-8d4f7f80-ffe2-11e9-8138-fd328f2fae3e.png)

**Comment by BohdanNikoletti** [comment]
Made update. Big thank to all your attention. Also going to publish on GitHub actual SameFace.framework stay tuned.
