### ISSUE TITLE
found nil unwrapping optional

### ISSUE THREAD

**Issue by markmansur** [BohdanNikoletti/SFaceCompare#19]
im getting the following error when comparing.

```
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/markmansur/Library/Developer/Xcode/DerivedData/ExamBee2-hkvxxdslrghnmcbiugcsagiojfve/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SFaceCompare.build/DerivedSources/CoreMLGenerated/Faces/Faces.swift, line 75
```

**Comment by BohdanNikoletti** [comment]
Try with new version. Also did you include [Faces.mlmodel](https://github.com/BohdanNikoletti/SFaceCompare#import-facesmlmodel)

**Comment by horrion** [comment]
@markmansur I had the exact same problem. After downloading the mlmodel file and including it in the root directory of the project, everything works as expected!

**Comment by markmansur** [comment]
Strange that this didnt work right after installing the pod, closing this issue.
