### ISSUE TITLE
SameFace.framework source / project missing.

### ISSUE THREAD

**Issue by littleowl** [BohdanNikoletti/SFaceCompare#2]
Hi, great job putting this together. I was hoping that you could supply the source or project to the embedded SameFace.framework. It currently only supports iOS 11.3 and up which unfortunately does not need my requirements. I would like to either be able to build for iOS 11.0 and make anything that requires 11.3 optional, or see the source so that I can remove dlib and opencv as a dependency, which I believe I could do if I knew a couple more implementation details. Thx!

**Comment by BohdanNikoletti** [comment]
@littleowl  iOS 11.3 came from dlib. And it plays important role in face preparation before matching. I'll pull SameFace.framework in this repo in a different branch(on this week). So u can make changes. And add a rebuilt version of dlib for ios 11. I'll be glad to get help from u.

**Comment by littleowl** [comment]
Hi @BohdanNikoletti - Thanks you so much for getting back to me, I really appreciate it. I did however manage to remove the dependency of the SameFace.framework altogether. 
Here were my steps:

- determined size and shape of input tensor (BGR data without alpha at 96x96)
- while debugging, I exported many of these images that where prepared for the network.
  - I aligned them all in an image editor with transparency.
  - This gave me the following points: leftEyeOutsideCorner: {x: 16, y: 16}, rightEyeOutsideCorner: {x: 80, y: 16}, bottomOfNose: {x: 48, y: 48} (optionally if you wanted to use nose tip - {x: 48, y: 40})
    - If I had the code, I might not have needed this step.
- I used the Vision framework like you have, But replaced with Landmark detection. dlib basically does the same thing, but Vision does it without needing to convert the image to another format, nor include the 80ish mb of the data model.
- Researched the math needed to create affine transform matrices between two triangles. 
- Used Accelerate and vImage
  - convert source to vImage_buffer and then to planner buffers per channel.
  - take out the alpha channel
  - create planer output buffers and use the calculated affine transform inverse to map just the 96x96 pixels of the output image to pixels in the source image
    - there is actually a vImage function for this, but I need to put more time into getting it to work.
  - convert to interlaced image again and export a CGImage
- The resulting images where aligned just like those from dlib and openCV, except, SameFace produced vertical line artifacts that might have an adverse effect.
- Used an Accelerate.framework function (faster) to calculate the distance squared between two neural network outputs
- Additionally, I implemented a DBScan algorithm for face clustering. (I was processing my entire photo library) 
  - Created distance matrix for every face so the distance scores between two faces only need to be calculated once.
  - DBScan stands for Density Based Spatial Clustering of Applications with Noise.
    - gives you two parameters to work with. minimum to find in a cluster, and an epsilon distance.

After the fact, it seemed to work as good or maybe better than previously. (no line artifacts in input images of neural network might have some effect.)
If you are interested in removing the dependency for this project too, then, I would be glad to help.

**Comment by BohdanNikoletti** [comment]
@littleowl  Man,  sorry for long response. I feel bad about this. had a lot of work todo. I think u understand. So let's back to job. I've published SameFace.framework repo to [bit-bucket](https://bitbucket.org/Nikoletti/sameface/src/master/). It's a little bit ugly and sweaty code in some places so be ready) . In case you will made some changes and improvement to this repo I will transfer it to GitHub and will make better structure.

**Comment by ozgurshn** [comment]
hi @BohdanNikoletti the bit-bucket link seems private, have u got a chance to publish src of SameFace in github?

**Comment by dipang90** [comment]
@littleowl  @BohdanNikoletti  dyld: Library not loaded: @rpath/SameFace.framework/SameFace in the pod 'SFaceCompare' 3.0 version. 
Any solution? Please
