### ISSUE TITLE
SameFace-Swift5.1.3- problem

### ISSUE THREAD

**Issue by AnteCepic** [BohdanNikoletti/SFaceCompare#20]
Hello,
with the new Xcode 11.3 again the SameFace cannot be integrated, because the Xcode now uses Swift 5.1.3.
Would you please recompile again ?
Is there a way that this can be made independent of the Swift- version to avoid such problems?
There were some hints in the previous tickets.
Thanks
Ante

**Comment by SreeniiOSteam** [comment]
I am also facing the same error. How to solve this?

**Comment by dev-dapis** [comment]
Has anyone solved this problem?

**Comment by horrion** [comment]
Hey everyone, I've recompiled the framework for Swift 5.2 which now provides module stability. If @BohdanNikoletti accepts [my pull request](https://github.com/BohdanNikoletti/SFaceCompare/pull/26), we'll soon have an updated version available on CocoaPods.
