### ISSUE TITLE
problem to Swift 5.1.3.

### ISSUE THREAD

**Issue by dev-dapis** [BohdanNikoletti/SFaceCompare#22]
Hello, it is an interesting project, I only have the problem with swift in version 5 and that xcode now uses it, could you recompile the library, please ..

Thank you.

**Comment by thedore17** [comment]
Any solution to this?

**Comment by horrion** [comment]
Swift 5.1 introduced module stability, so once we get @BohdanNikoletti to update SameFace.framework to Swift 5.1, we should be fine for the foreseeable future. Unfortunately, the source files for SameFace.framework weren't provided.

**Comment by horrion** [comment]
Issue has been solved, [just waiting for the pull request to be accepted](https://github.com/BohdanNikoletti/SFaceCompare/pull/26).

**Comment by BohdanNikoletti** [comment]
Make update of code base also include @horrion changes
