### ISSUE TITLE
Please update SameFace.framework to Swift 5.1 for module stability

### ISSUE THREAD

**Issue by horrion** [BohdanNikoletti/SFaceCompare#25]
Hi @BohdanNikoletti 

I'm currently working on a fix for the recognition issue. Unfortunately, SameFace.framework was compiled with a Swift 4.2 compiler, leading to the error `Module compiled with Swift 4.2 cannot be imported by the Swift 5.2 compiler`. This means that I can't compile SFaceCompare for debugging purposes on any remotely current version of Xcode. 

Swift 5.1 introduced module stability, so I'd kindly ask you to update SameFace.framework to at least Swift 5.1. Unfortunately the source files for SameFace.framework aren't provided, so it looks like you're the only person capable of updating the framework. Would greatly appreciate an update to Swift 5.1!

**Comment by horrion** [comment]
Follow up: I've recompiled the framework after finding the separate repository. Upon accepting [my pull request](https://github.com/BohdanNikoletti/SFaceCompare/pull/26) this issue can be closed.

**Comment by BohdanNikoletti** [comment]
Merged your PR also some updates
