### ISSUE TITLE
Can't compile for mobile device 

### ISSUE THREAD

**Issue by AfrozZaheer** [BohdanNikoletti/SFaceCompare#3]
hi, 
great library you have there, I have problem compiling it on mobile device it throughs an error. attached is a screen shot. Please help ASAP. 

Thanks

![screenshot 2018-11-26 at 1 10 07 pm](https://user-images.githubusercontent.com/25176835/49000831-9e5e0280-f17c-11e8-91bd-0fd668c2c586.png)

**Comment by BohdanNikoletti** [comment]
Set ENABLE_BITCODE in project build settings to 'NO'

**Comment by AfrozZaheer** [comment]
Already did... 

Thank you very much 👍
