### ISSUE TITLE
Library crashing 

### ISSUE THREAD

**Issue by bhavuk-webkul** [BohdanNikoletti/SFaceCompare#4]
here app is crashing
 class var urlOfModelInThisBundle : URL {
        let bundle = Bundle(for: Faces.self)
        return bundle.url(forResource: "Faces", withExtension:"mlmodelc")!
    }

http://prntscr.com/mk7yua

**Comment by BohdanNikoletti** [comment]
@bhavuk-webkul  yep( I know ( I forget mentioned that u need to copy Faces.mlmodel from SFaceCompare/Example/SFaceCompare/Faces.mlmodel to your app directory. And that should work fine. I don't remember what issues I've faced trying to Integrate .mlmodel file in pod bundle. So if you have any ideas welcome.

**Comment by bhavuk-webkul** [comment]
Yes, this issue solved by me yesterday but here I can see two different faces also showing the true result. this is not working fine for identical faces.

**Comment by bhavuk-webkul** [comment]
Yes, this issue solved by me yesterday but here I can see two different faces also showing the true result. this is not working fine for identical faces.
