### ISSUE TITLE
Faces not matching correctly

### ISSUE THREAD

**Issue by arshadsk5** [BohdanNikoletti/SFaceCompare#5]
I used this library, i took photo of mine and my friend using camera after loading it says "Faces are the same". How it is working.

![Skype_Picture](https://user-images.githubusercontent.com/24600303/54972334-24fee100-4fb1-11e9-9c47-a0810919e832.jpeg)

**Comment by BohdanNikoletti** [comment]
The first picture was taken in profile and second is a photo in full face. Pls try to take your friend and yours faces in full and compare results.

**Comment by arshadsk5** [comment]
Even i tried that, please see the below screen shot.
![Skype_Picture (1)](https://user-images.githubusercontent.com/24600303/55049662-1d077580-5073-11e9-9e85-efd981a36253.jpeg)

**Comment by taimurimam** [comment]
yes I also face this problem. It working fine but some time it does not work do you have any solution for that.

**Comment by BohdanNikoletti** [comment]
Agree, sometimes it doesn't work. There isn't any solution for it right now. I'm sorry. That this doesn't work in some cases.

**Comment by arshadsk5** [comment]
It didn't work even for the first time, may i know when it is not working for you.

**Comment by BohdanNikoletti** [comment]
I've used OpenFace trained model. About restrictions and detail of trained model you can read [here](https://cmusatyalab.github.io/openface/).

**Comment by BohdanNikoletti** [comment]
https://www.researchgate.net/publication/328186690_Evaluating_OpenFace_an_open-source_automatic_facial_comparison_algorithm_for_forensics
More about this.

**Comment by taimurimam** [comment]
can it be compared one face in one image and same face with multiple face with 2nd image.

**Comment by BohdanNikoletti** [comment]
> can it be compared one face in one image and same face with multiple face with 2nd image.
It's can be nice to have feature.

**Comment by AsadFarooq5777** [comment]
facing same problem...

**Comment by horrion** [comment]
Same problem here! 

I've got a suspicion though: The authors of the model state that the faces to be evaluated basically need to be cut out of the complete photo to enable face recognition at >99% confidence. I don't think the face is being cut from the complete photo here? I'll test this, but [Apple's vision API](https://developer.apple.com/documentation/vision/tracking_the_user_s_face_in_real_time) can be used to track faces. The acquired coordinates can then be used to crop the photo.

**Comment by dipang90** [comment]
@horrion @arshadsk5 @taimurimam  Is there any alternative solution for this library? I have also same issue with wrong face match.

**Comment by BohdanNikoletti** [comment]
> Same problem here!
> 
> I've got a suspicion though: The authors of the model state that the faces to be evaluated basically need to be cut out of the complete photo to enable face recognition at >99% confidence. I don't think the face is being cut from the complete photo here? I'll test this, but [Apple's vision API](https://developer.apple.com/documentation/vision/tracking_the_user_s_face_in_real_time) can be used to track faces. The acquired coordinates can then be used to crop the photo.

Faces are created and prepared for model. You can see the code of the back-end repo [here](https://github.com/BohdanNikoletti/SameFace)
