### ISSUE TITLE
not work for IOS 12.2

### ISSUE THREAD

**Issue by timteemo** [BohdanNikoletti/SFaceCompare#7]
SameFace do not support Swift 5.0

**Comment by unpluggedk** [comment]
+1 on that, can someone help?
Thanks!

**Comment by BohdanNikoletti** [comment]
I'm going to fix this on weekend. Stay tuned.

**Comment by BohdanNikoletti** [comment]
fixed in 2.6.3

**Comment by SourabhMahna** [comment]
Code not matching same faces for me as well. It is able to match downloaded images but when i clicked image of myself, it is not able to match.
![IMG_884848626F1C-1](https://user-images.githubusercontent.com/50948399/58243548-74be1680-7d6e-11e9-9777-2d7882e85a0b.jpeg)
