### ISSUE TITLE
Could not find module 'SameFace' for architecture 'arm64'; found: x86_64

### ISSUE THREAD

**Issue by thedore17** [BohdanNikoletti/SFaceCompare#8]
I'm receiving this error only when I build for device.

Line 10 of SFaceCompare.swift: import SameFace

Throws: "Could not find module 'SameFace' for architecture 'arm64'; found: x86_64"

Anyone else having this issue after updating XCode?

**Comment by BohdanNikoletti** [comment]
@thedore17 😨I forgot to make SameFace universal framework in latest update. To support both iOS and simulator. My bad. Going to fix this on weekends. Stay tuned.

**Comment by thedore17** [comment]
So dumb that XCode doesn't do it by default! I was so close to getting my project working :( Anything I can do to help?

**Comment by BohdanNikoletti** [comment]
Thanks, I've done already. Going to update today. Just after work)

**Comment by BohdanNikoletti** [comment]
Fixed in latest release.
