### ISSUE TITLE
Clicked image not able to match IOS12.2

### ISSUE THREAD

**Issue by SourabhMahna** [BohdanNikoletti/SFaceCompare#9]
![IMG_884848626F1C-1](https://user-images.githubusercontent.com/50948399/58243630-9c14e380-7d6e-11e9-9d25-be8bb7801f00.jpeg)
Not able to match clicked image.

**Comment by BohdanNikoletti** [comment]
Pls read [this](https://github.com/BohdanNikoletti/SFaceCompare/issues/5#issuecomment-477549504) unfortunately model has some limitations.
